controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true
    #Load each controller

    arm_controller:
      type: position_controllers/JointGroupPositionController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - joint1
      - joint2
      - joint3
      - joint4
      - right_finger_joint
      - left_finger_joint
  
    interface_name: position
  
    gains:
        joint1: {p: 30.0, i: 0.0, d: 4.0}
        joint2: {p: 6.0, i: 0.0, d: 3.0}
        joint3: {p: 15.0, i: 0.0,  d: 8.0} # More P to overcome friction
        joint4: {p: 4.0, i: 0.0, d: 1.5}
        right_finger_joint: {p: 3.0, i: 0.0, d: 0.1}
        left_finger_joint:  {p: 3.0, i: 0.0, d: 0.1}


